### ISSUE TITLE
Broken links after install

### ISSUE THREAD

**Issue by pablorq** [nayibor/inventory_sys#1]
Hi!

After install, the system has some broken links and says this:

Warning: include(C:\wamp\www\inventory_sys\Cake\bootstrap.php): failed to open stream: No such file or directory in C:\wamp\www\inventory_sys\app\webroot\index.php on line 104

After copy the all folder from inventory_sys\lib\Cake to inventory_sys\Cake, I can see the login screen with a broken link to an image.

But the login page doesn't work.

Any ideas?

Regards...

**Comment by nayibor** [comment]
it may have to do with enabling mod_rewrite for apache on your  wamp server installation . 
try enabling mod_rewrite on apache and try again .
this is a link to how to do it 
http://www.orchidbox.com/post.php?title=How_to_enable_mod_rewrite_module_in_apache_in_xampp_wamp

**Comment by pablorq** [comment]
Hi!

Just updated wamp to v3.1 and now in the page http://127.0.0.1/inventory_sys/ I have the login page.

When trying to log in with user: inv@inv.com pass: 123 I have this error:

Warning (512): Invalid salt: buHJE9e4ip1pAUGHC9DN9paVQQkH4qupM4sQlW6O$7c6679383d2a1aa476d9d6c273aeefa5f394a32df8bcbc2c009d829913c3f06a for blowfish Please visit http://www.php.net/crypt and read the appropriate section for building blowfish salts. [CORE\Cake\Utility\Security.php, line 290]

Any idea?

Regards...

**Comment by nayibor** [comment]
please run the sql file again .
dbase/inventory_sys_def_install.sql
you can also get a new copy of the application from the master branch.
have made some changes .
please use google chrome/firefox also for your browser .
the user interface is optimized for google chrome/firefox

**Comment by pablorq** [comment]
Hi!

I've downloaded again the app from master branch. Droped the previous DB. Delete previous web server install.

Tasks done:
- Unzip the app in: C:\wamp64\www\inventory_sys
- Create and import the DB from dbase/inventory_sys_def_install.sql
- Using Firefox 58.0.2

No error now. I can see the login page. But the login (inv@inv.com:123) doesn't work.

Any idea?

Regards...

**Comment by nayibor** [comment]
please drop the db (inventory_sys_def_install.sql) and reload it again .
have edited the initial admin password in it .
if logging  in still does not work ,go to this [site](http://www.passwordtool.hu/blowfish-password-hash-generator) and generate a  hash using the 123  password and then update the password field of the users table for the user **inv@inv.com** with the hash generated .

**Comment by pablorq** [comment]
Hi!

When reinstall the system I forgot to setup the db!

Now it works! 

Tx!

**Comment by nayibor** [comment]
Nyce !! .
